In [1]:
import os
#创建文件夹
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
#创建文件
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [2]:
import pandas as pd
#read_csv()
data = pd.read_csv(data_file)
print(data)
#注意，“NaN”项代表缺失值。

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [19]:
#为了处理缺失的数据，典型的方法包括插值法和删除法
#这里，我们将考虑插值法
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
#fillna() 填一个值  
#mean() 求均值
print(inputs)


   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [20]:
#对于`inputs`中的类别值或离散值，我们将“NaN”视为一个类别。
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)
#函数get_dummies()


   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [24]:
#把所有内容都变成了数值，所以可以转化为张量
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

#tensor和array的区别
# 张量 数组
#


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [25]:
a=torch.arange(12)
b=a.reshape(3,4)
b[:]=2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])