In [73]:
#我们实例化两个标量，并执行一些熟悉的算术运算，即加法、乘法、除法和指数。我们实例化两个标量，并执行一些熟悉的算术运算，即加法、乘法、除法和指数。
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [74]:
#可以将向量视为标量值组成的列表。 我们将这些标量值称为向量的元素（element）或分量（component）。
#我们通过一维张量处理向量。一般来说，张量可以具有任意长度，取决于机器的内存限制。
x = torch.arange(4)
x


tensor([0, 1, 2, 3])

标量、向量、张量的区别
1.标量Scalar
    一个标量就是一个单独的数，一般用小写的的变量名称表示。
2. 向量Vector
   一个向量就是一列数，这些数是有序排列的。
3. 矩阵Matrix
   矩阵是二维数组，其中的每一个元素被两个索引所确定。
4. 张量
   几何代数中定义的张量是基于向量和矩阵的推广，通俗一点理解的话，我们可以将标量视为零阶张量，矢量视为一阶张量，那么矩阵就是二阶张量。
   

   

In [75]:
#在代码中，我们通过张量的索引来访问任一元素。
x[3]
#索引从0开始

tensor(3)

In [76]:
#访问张量的长度
len(x)

4

In [77]:
#访问张量的形状
#只有一个轴的张量，形状只有一个元素
x.shape

torch.Size([4])

In [78]:
#通过制定分量来创建矩阵
A = torch.arange(20).reshape(4,5)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [79]:
#矩阵的转置
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [80]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B
#B是对称矩阵

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [81]:
B == B.T
#B和B的转置相等

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [82]:
#就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。
#向量是一阶张量，矩阵是二阶张量
X = torch.arange(24).reshape(2, 3, 4)
X


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [83]:
 #张量算法的基本性质
 #给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量
 A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B
#clone()函数，分配新内存


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [84]:
#两个矩阵的按元素乘法称为Hadamard积
A * B


tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [85]:
#将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape


(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [86]:
#我们可以对任意张量进行的一个有用的操作是计算其元素的和。
x = torch.arange(4, dtype=torch.float32)
x, x.sum()
#sum()函数


(tensor([0., 1., 2., 3.]), tensor(6.))

In [87]:
A.shape, A.sum()
#不管张量什么形状、sum()都是一个标量


(torch.Size([5, 4]), tensor(190.))

In [88]:
#调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。 我们还可以指定张量沿哪一个轴来通过求和降低维度。
A.shape
A_sum_axis0=A.sum(axis=0)   #将行数压缩成一行
A_sum_axis0
A_sum_axis0.shape  #torch.Size([4])
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [89]:
#指定axis=1将通过汇总所有列的元素降维
A_sum_axis1 = A.sum(axis=1)  #变成一列
A_sum_axis1, A_sum_axis1.shape


(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [90]:
#沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。
A.sum(),A.sum(axis=[0,1])    #效果一样
A.sum(axis=[0,1]).shape

torch.Size([])

In [91]:
#一个与求和相关的量是平均值（mean或average）。 我们通过将总和除以元素总数来计算平均值。 在代码中，我们可以调用函数来计算任意形状张量的平均值。
A
A.sum(),A.sum()/A.numel(),A.mean()
#mean（） 求平均值    numel()求元素数量


(tensor(190.), tensor(9.5000), tensor(9.5000))

In [92]:
#非降维求和  keepdims=True
A
sum_A = A.sum(axis=1,keepdims=True)
sum_A2 = A.sum(axis=1)
A,A.shape,sum_A,sum_A.shape,sum_A2,sum_A2.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

In [93]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [94]:
#果我们想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），我们可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。
A,A.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [95]:
a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [96]:
a.sum().shape   #torch.Size([]) 代表是一个标量
a.sum(axis=0).shape
a.sum(axis=1).shape

torch.Size([2, 4])

In [101]:
a,a.sum(axis=0,keepdims=True)
a,a.sum(axis=1,keepdims=True)
a,a.sum(axis=2,keepdims=True)
a,a.sum(axis=[0,2],keepdims=True)

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[[8.],
          [8.],
          [8.],
          [8.],
          [8.]]]))

深度学习为什么用张量？
copy和clone的区别？
copy不一定复制内存，clone一定可以
